name: Development
run-name: Compilation & Quality Checks

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
    branches:
      - '*'
      - '!develop'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Check current timezone
        run: date

      - name: Run Unit Tests
        env:
          TZ: UTC
        run: npm run test:ci

